version: '3.7'
services:
    postgres-comfort-db:
        image: postgres:10.5
        environment:
          - POSTGRES_USER=comfort
          - POSTGRES_PASSWORD=comfort
          - POSTGRES_DB=comfort_sponsored
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./select.sql:/docker-entrypoint-initdb.d/select.sql
          #- ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          #- ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

